Repository mobileappdevhm19/lust-LibraryUniversalSwissTool, pull requests merged in 2019-05, with the labels that each got.

#38 Add baumpfleger.yml and ignore master and develop
  .github/baumpfleger.yml
Labels: enhancement

#40 add horizontal prototype in justinmind
  design/hPrototype/HorizontalPrototype.vp
  design/hPrototype/Screenshots/Book_Finding.png
  design/hPrototype/Screenshots/Check In_Out.png
  design/hPrototype/Screenshots/Map.png
  design/hPrototype/Screenshots/Pomodoro.png
  design/hPrototype/Screenshots/Screenshot_2019-05-02-11-03-13-278_com.libuniswisstool.lust.png
  design/hPrototype/Screenshots/Statistics.png
  design/hPrototype/Screenshots/Tutoring Chat.png
  design/hPrototype/Screenshots/Tutoring.png
Labels: prototyping

#37 Make readme files great again
  README.md
Labels: enhancement, keep-branch

#71 Feature/menu drawer
  lust/lib/main.dart
  lust/lib/views/capacityPage.dart
  lust/lib/widgets/widgetCreator.dart
Labels: Frontend
